Heating_getVitoBetriebsart|$R1|$E1
Heating_getVitoTempRaumNorSoll|$2|$E2
Heating_getVitoTempRaumRedSoll|$3|$E3
Heating_getVitoTempAussen|$4|$E4
Heating_getVitoTempWWIst|$5|$E5
Heating_getVitoTempWWSoll|$6|$E6
Heating_getVitoTempSpeicher|$7|$E7
Heating_getVitoTempWWAuslauf|$8|$E8
Heating_getVitoStatusPumpeSpeicher|$R9|$E9
Heating_getVitoTempKesselIst|$10|$E10
Heating_getVitoTempKesselSoll|$11|$E11
Heating_getVitoStatusFlamme|$R12|$E12
Heating_getVitoStartsBrenner|$13|$E13
Heating_getVitoStatusPumpeIntern|$R14|$E14
Heating_getVitoDrehzahlPumpeIntern|$15|$E15
Heating_getVitoKennlinieNeigung|$16|$E16
Heating_getVitoKennlinieNiveau|$17|$E17
Heating_getVitoBetriebsartHK|$R18|$E18
Heating_getVitoTempVLSoll|$19|$E19
Heating_getVitoTempRLIst|$20|$E20
Heating_getVitoStatusPumpeHK|$R21|$E21
Heating_getVitoStatusPumpeZirku|$R22|$E22
Heating_getVitoStatusUmschaltventil|$R23|$E23
Heating_getVitoStatusStoerung|$R24|$E24
