# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: VControld add-on"
  org.opencontainers.image.description: "VControld add-ons."
  org.opencontainers.image.source: "https://github.com/hholle/ha-addons/tree/main/vcontrold"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
